### ISSUE TITLE
Trouble linking files with dot notated names 

### ISSUE THREAD

**Issue by lessthanzero** [jekyll/jekyll-assets#350] opened 2016-11-29 22:08 UTC
Hi! I have a fairly straightforward setup: jekyll-based website with jekyll-assets plugin and bower as a package manager. When I include something like `{% js lib %}` in template (where `lib` is installed via bower) it works fine. But when I try to use `{% js jquery.lib %}` it doesn't include anything and jekyll outputs that the file cannot be found. `jquery.lib.js` is, however, in place. Bower and Jekyll settings seems to be fine; `.bowerrc`/`_config.yml` are correct too. Bower distros are located in `_assets/bower`. Jekyll 3.3.0, Bower 1.8.0.

I experimented a bit, it doesn't work with dot notation in file names, as I understood. Haven't found anything relevant in docs. What am I doing wrong?

Any help will be greatly appreciated. Thanks!

**Comment by envygeeks** [comment] 2016-11-30 07:20
You are probably doing nothing wrong.  I've noticed this too, but I am not able to resolve it since we resolve our paths (read: names) with Sprockets itself, and haven't quite figured out if it's a bug in sprockets or intended behavior.  If you have problems try using the full name "jquery.lib.js" and other than that the most I can do is look into if it's reporting the right mime-type.

**Comment by envygeeks** [comment] 2017-06-19 04:33
I'm gonna close this since it's tracked in Sprockets.  If they (or you, or even I) find it's a bug here in Jekyll-Assets, please do let me know and I'll happily reopen!

**Closed by envygeeks** 2017-06-19 04:33 UTC
