### ISSUE TITLE
Error:  undefined method `logical_path' for nil:NilClass

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-assets#318] opened 2016-08-11 18:40 UTC
Hi there,

I have a problem. If I delete some images from my `_assets` folder and delete any code associated with them, I keep getting this error:

```
jekyll 3.2.0 | Error:  undefined method `logical_path' for nil:NilClass
```

Is there any way to fix it?

**Comment by envygeeks** [comment] 2016-08-11 21:06
Clear your .asset-cache folder and the problem will disappear.

**Comment by envygeeks** [comment] 2016-08-11 21:25
I am unable to reproduce this so if you can provide the full error (with --trace) that would be great!

**Comment by iloveip** [comment] 2016-08-13 11:57
@envygeeks Thank you very much for your reply. I don't have `.asset-cache` folder, I guess I've deleted it before, because I was getting some errors. Here is the full error after renaming the images in `_assets/images/` folder.

```
Svetlanas-MacBook-Pro:iloveip svetlana$ jekyll serve --trace
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
Configuration file: /Users/svetlana/Desktop/iloveip/_config.yml
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007fbe62daaac0@/Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-6.3.7/lib/autoprefixer-rails/sprockets.rb:37>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from install at /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-6.3.7/lib/autoprefixer-rails/sprockets.rb:37)
                    Caching disabled however, if you use proxies it could still possibly be created.
            Source: /Users/svetlana/Desktop/iloveip
       Destination: /Users/svetlana/Desktop/iloveip/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007fbe636a1750@/Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-6.3.7/lib/autoprefixer-rails/sprockets.rb:37>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from install at /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-6.3.7/lib/autoprefixer-rails/sprockets.rb:37)
                    Caching disabled however, if you use proxies it could still possibly be created.
       Deprecation: posts.each should be changed toposts.docs.each.
                    Called by /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-last-modified-at-0.3.4/lib/jekyll-last-modified-at/generator.rb:7:in `block in generate'.
                    Asset inconsitency, expected 
/Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/env.rb:292:in `map': undefined method `logical_path' for nil:NilClass (NoMethodError)
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/env.rb:292:in `write_all'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/hooks/jekyll/write.rb:9:in `block in <top (required)>'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/hooks.rb:98:in `call'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/hooks.rb:98:in `block in trigger'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/hooks.rb:97:in `each'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/hooks.rb:97:in `trigger'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:215:in `write'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:71:in `process'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/command.rb:26:in `process_site'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/lib/jekyll/commands/serve.rb:36:in `block (2 levels) in init_with_program'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.2.0/exe/jekyll:13:in `<top (required)>'
	from /Users/svetlana/.rbenv/versions/2.2.3/bin/jekyll:23:in `load'
	from /Users/svetlana/.rbenv/versions/2.2.3/bin/jekyll:23:in `<main>'
Svetlanas-MacBook-Pro:iloveip svetlana$ 
```

**Comment by durfee** [comment] 2016-08-17 20:33
I (sort of) resolved this by doing `jekyll clean`, which resets the count on `manifest.all.size` in [env.rb:275](https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/env.rb#L275) which was causing the problem.

Afterwards however, it seems to unset the load path and then can't find any of the assets, giving me:

```
[2016-08-17 13:21:08] ERROR `/assets/logo.png' not found.
[2016-08-17 13:21:08] ERROR `/assets/National-Light.otf' not found.
[2016-08-17 13:21:08] ERROR `/assets/NationalApp-Book.ttf' not found.
[2016-08-17 13:21:08] ERROR `/assets/NationalApp-Medium.ttf' not found.
[2016-08-17 13:21:08] ERROR `/assets/60-percent-gplaypattern-subtlepatterns.png' not found.
[2016-08-17 13:21:08] ERROR `/assets/disclosure.svg' not found.
[2016-08-17 13:21:08] ERROR `/assets/more-than.jpg' not found.
```
Which is monkey wrench fixable by just dragging and dropping all your 'missing' files from _assets/ to your _site/assets/. Crude, but it works.

**Comment by kvz** [comment] 2016-10-12 18:32
`rm -rf .asset-cache/` didn't work for me `bundle exec jekyll clean` did, thanks!

**Comment by envygeeks** [comment] 2017-10-07 08:11
This is fixed in 3.x, thanks for the bug report!

**Closed by envygeeks** 2017-10-07 08:11 UTC
Labels: bug, cant-reproduce
