### ISSUE TITLE
Need some help understanding how to work with this gem

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-assets#272] opened 2016-05-04 13:15 UTC
Hi there,

Could you please give some live examples of websites using this gem on GitHub? I've read the documentation but I'm not sure if I'm doing this right as I keep getting a message that my css and js files are not found.

I installed the gem and created `_assets` folder with the following folders inside:

 ```
project-name/
├── _assets/
|   ├── images/ 
|   ├── javascripts/
|   ├── stylesheets/
```

In `_assets/javascripts` folder I have `main.js` file. In `_assets/stylesheets` folder I have `reset.scss`, `normalize.scss` files and `main.scss` file, which looks like this:

```
@import "reset";
@import "normalize";
```

In the `<head>` I add `{% stylesheet main %} ` and `{% javascript main %}`. But when I serve the site, I get the following errors:

```
[2016-05-04 15:57:28] ERROR `/assets/main.css' not found.
[2016-05-04 15:57:28] ERROR `/assets/main.js' not found.
```

I would really appreciate your help.

**Comment by envygeeks** [comment] 2016-05-04 13:21
Remove the `.asset-cache` folder and restart Jekyll.  

If you have any further questions or comments that are not Jekyll bugs please ask your questions at https://talk.jekyllrb.com, which is where we hold all non-bug related discussions.

Thanks!

**Comment by iloveip** [comment] 2016-05-04 19:15
@envygeeks Thank you very much for your reply! I deleted the `.asset-cache` folder, but I still keep getting these error messages.

It's written in the docs: "If you do not understand something in our documentation please feel free to file a ticket and it will be explained and the documentation updated". That's why I decided to file an issue here.

**Comment by envygeeks** [comment] 2016-05-04 19:23
@iloveip I do apologize for that, it does need to be updated as that was written before we implemented the forums and started pushing users there.  That said, if you think this is a bug rather than a user error, I'll need more information, lots more.

1. Ruby Version
2. Source (without it, this is a WONTFIX because it's an edge.)
3. Operation System

I understand the need for source might be intrusive so a test-case repo that can replicate the issue would be just as well.  In this case, it's obligatory because nearly 100% of our tests rely on this fundamental behavior to pass, so we'll need something that can reliably replicate the issue so we can shim the source and step through it finding out where the problem is.

If you can still reliably reproduce it and want to provide that stuff, I'd be more than happy to take the time to see what i can figure out for you and either issue a fix as soon as I find out what's wrong or tell you what is wrong with your source so it can be resolved there.

**Comment by iloveip** [comment] 2016-05-04 19:38
@envygeeks Ok, thank you very much. I will try to figure it out myself, and if it doesn't work, I'll follow the instructions above.

Could you please clarify by 'Remove the `.asset-cache` folder' you mean delete it from source folder, or add it to exclude list in `_config.yml` file, or something else? Because after deleting the folder gets generated again.

**Comment by envygeeks** [comment] 2016-05-04 19:55
We already exclude that folder for you.  I meant delete

**Comment by iloveip** [comment] 2016-05-04 20:23
@envygeeks Yes, deleting this folder solves the problem. But it gets generated again with every new build. Is there anyway to delete it permanently?

**Comment by envygeeks** [comment] 2016-05-04 20:52
@iloveip There is, set the cache to `false` but it should be entirely, however, there are plans in 2.2.6 which will be released in the next few days to delete the asset-cache on Jekyll boot to prevent those races and give users a clean asset chain.

***WARNING NOTE: If you remove the `.asset-cache` it will still get created for proxied images, those have an always on cache because ImageMagick is expensive and removing `.asset-cache` for all other assets will result in build times 100x slower (probably slightly hyperbolic,) our builds go from 0.1s to 7s though, over 700x slower.***

**Comment by iloveip** [comment] 2016-05-05 21:28
@envygeeks Thank you very much for your help. I don't know if it's a bug, but the files were not generated with incremental build. If I simply run `bundle exec jekyll serve` without `--incremental`, everything works ok.

**Comment by envygeeks** [comment] 2016-05-05 21:50
That is not a bug, incremental regeneration is experimental and we make no promise that your assets will build or rebuild when it's enabled because it had some problems that needed to be addressed upstream.  Sorry.

**Closed** 2016-05-05 21:57 UTC
Labels: upstream:jekyll-issue, wontfix

**Comment by iloveip** [comment] 2016-05-06 08:56
@envygeeks Ok, thank you very much for the information.
