### ISSUE TITLE
Cannot pass classes to inlined SVGs

### ISSUE THREAD

**Issue by admhlt** [jekyll/jekyll-assets#306] opened 2016-07-19 20:29 UTC
If I use `{% asset my_logo.svg class:"logo logo--inline" %}` to load an SVG inline, jekyll-assets doesn't apply any of the classes to the SVG element.

``` html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 88 88">
...
</svg>
```

I understand that passing in classes doesn't make sense when inlining some assets, but it would be nice to be able to pass classes to inlined SVGs.

I'd like to get:

``` html
<svg class="logo logo--inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 88 88">
...
</svg>
```

**Comment by envygeeks** [comment] 2016-07-19 21:59
We'd have to create a whole new tag to do what you want, asset was designed to simply return the path and nothing else so any data you pass to us that is not a proxy gets ignored (`#to_html` isn't even ran.)

**Comment by envygeeks** [comment] 2017-10-10 08:00
Fixed in 3.x which is due today or tomorrow.

**Closed by envygeeks** 2017-10-10 08:01 UTC
Labels: enhancement

**Comment by admhlt** [comment] 2017-10-10 15:14
Amazing! Thanks Jordon.

**Comment by RhysyG** [comment] 2017-12-21 00:44
Hi guys,

This is great. What's the markup look like?

{% include icons/menu.svg %}

**Comment by jondavidjohn** [comment] 2018-10-05 22:05
Same, curious on the syntax here 🤔

**Comment by envygeeks** [comment] 2018-10-05 22:12
https://github.com/envygeeks/jekyll-assets#arguments

**Comment by jondavidjohn** [comment] 2018-10-05 22:30
So specifically, to add a class to an inline svg, it would be something like

```
{% asset thing.svg @inline class='list of classes' %}
```

?

I tried that and it wasn't working, could be that the svg already has a class applied to the svg tag in the file?
