### ISSUE TITLE
Liquid processing of assets

### ISSUE THREAD

**Issue by charliesneath** [jekyll/jekyll-assets#208] opened 2015-11-19 14:58 UTC
Example case: 

The first lines of `_assets/css/main.scss`:

```
---
# Jekyll front matter
---
@charset "utf-8";
@import 'fonts';
@import 'bourbon/bourbon';
@import 'neat/neat';
...
```

The SASS directory (where the SCSS partials are located) is updated in `_config.yml`:
```
sass:
  sass_dir: _assets/sass
```

When the site is built:

- `_assets/css/main.scss` is processed by Liquid
- `main.scss` is available as `{% stylesheet main %}`.

**Comment by envygeeks** [comment] 2015-11-19 15:23
Just for clarification what you want is:

1. The abilty to take `_assets/main/main.scss` and to parse the liquid.
2. The ability to use those liquid variables in your helpers.
3. The ability to get the final CSS via stylesheet.

Yes?

**Comment by envygeeks** [comment] 2015-11-19 15:24
> SCSS partials are imported, helper functions are processed, e.g. background: url(asset_path('background.jpg');

This is the part that's confusing me, you can already do that.

**Comment by charliesneath** [comment] 2015-11-19 15:36
> 1. The abilty to take `_assets/main/main.scss` and to parse the liquid.
> 2. The ability to use those liquid variables in your helpers.
> 3. The ability to get the final CSS via stylesheet.

Correct. I'm hoping this will resolve the following error I get when `_assets/main/main.scss` is processed by `jekyll-assets`:

```
Liquid Exception: Invalid CSS after "@charset "utf-8"": expected "{", was ";" (in /Users/charlie/GitHub/jekyll-test/_assets/sass/main.scss:4) in _includes/head.html, included in _layouts/default.html
```

> This is the part that's confusing me, you can already do that.

Updated, was confusing this with earlier issue.

**Comment by envygeeks** [comment] 2015-11-19 15:40
This is doable, I'll make sure it lands in 2.1 for you!

**Comment by charliesneath** [comment] 2015-11-19 15:43
Thank you!!

**Comment by charliesneath** [comment] 2015-11-19 17:17
Do you have a target release date?

**Comment by envygeeks** [comment] 2015-11-19 17:21
@charliesneath 2.1 is what it will be released as, but I've already built this feature, if you want to play with it today I can push it up but you'll have to use Master from your Gemfile.

**Comment by charliesneath** [comment] 2015-11-19 17:27
@envygeeks Definitely, thanks — would love to play around with it. 

What do you mean by Master in the Gemfile?

**Comment by envygeeks** [comment] 2015-11-19 17:28
@charliesneath do you use a Gemfile right now or do you do a global install?

**Comment by charliesneath** [comment] 2015-11-19 17:29
Gemfile

**Comment by envygeeks** [comment] 2015-11-19 17:31
You'll need to remove "gem 'jekyll-assets'" and replace it with:

```ruby
gem "jekyll-assets", :github => "jekyll/jekyll-assets"
```

And it will use our master source which is unreleased and give you the feature once I push it.

**Comment by envygeeks** [comment] 2015-11-19 17:31
Let me finish the tests and I'll push it up and ping you, shouldn't be more than hour if that.

**Comment by charliesneath** [comment] 2015-11-19 17:32
Excellent, thanks.

Just to clarify, the new line in the Gemfile would be:

`gem "jekyll-assets", :github => "jekyll/jekyll-assets"`

**Comment by envygeeks** [comment] 2015-11-19 17:33
Yes.

**Comment by charliesneath** [comment] 2015-11-19 17:34
:ok_hand:

**Comment by envygeeks** [comment] 2015-11-19 17:47
I'll leave this open until you confirm it's what you were looking for.

**Comment by charliesneath** [comment] 2015-11-19 18:28
Updated the Gemfile and `_config.yml`, moved all SCSS files to `_assets/sass/`, and using `{% stylesheet main%}` but still seeing same error:

```ruby
  Liquid Exception: Invalid CSS after "@charset "utf-8"": expected "{", was ";" in _includes/head.html, included in _layouts/default.html
```

 I've updated my test repo here: https://github.com/charliesneath/asset-test/commit/de66720be40e750cd72f4de1daf52a73bf0e037c

What other information can I provide?

**Comment by envygeeks** [comment] 2015-11-19 18:30
@charliesneath since it's just a test repo do you mind giving me write access so I can work out what the problem is and push up a fix to both jekyll-assets and that repo?

**Comment by charliesneath** [comment] 2015-11-19 21:39
@envygeeks sorry for delay on this, missed notification. just added you as collaborator on the repo.

**Comment by envygeeks** [comment] 2015-11-20 13:05
Okay, I've figured it out:

Move everything from `_sass` to `_assets/css` and move `css/main.scss` to _assets/css, don't alter them.  Then edit your `head.html` in `_includes` and use `{% stylesheet main %}` in place of your `link` and it will work once you do `jekyll s --watch`

**Comment by envygeeks** [comment] 2015-11-20 13:06
We don't work in conjunction with jekyll-sass-converter, we replace it in it's entirety.

**Comment by charliesneath** [comment] 2015-11-20 15:57
@envygeeks Seeing the same error after making above changes (on [`master`](https://github.com/charliesneath/asset-test)). 

Using `gem "jekyll-assets", :github => "jekyll/jekyll-assets"` in my `Gemfile`.

Using `{% stylesheet main %}` in `_includes/head.html`.

My SCSS is organized as follows:

```
_assets/
└─ css/
   └─ main.scss
   └─ _base.scss
   └─ ...other css
```

**Comment by envygeeks** [comment] 2015-11-20 17:59
What is the "same error"?

**Comment by envygeeks** [comment] 2015-11-20 18:01
You need to add `jekyll` to your Gemfile and "bundle install --path vendor/bundle" and use "bundle exec jekyll command" from now on to use our master source but other than that the only error you should get is because you didn't remove the `---` jekyll stuff from the top of your main.css.  We do not require frontmatter to process and we will actually error if you have frontmatter.

**Comment by charliesneath** [comment] 2015-11-20 18:32
The Liquid error was resolved when adding `jekyll` gem to `Gemfile`.

I'm getting thrown a new error:

```
Error reading file /Users/charlie/GitHub/asset-test/vendor/bundle/ruby/2.2.0/gems/jekyll-3.0.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.2.0/gems/jekyll-3.0.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

**Comment by envygeeks** [comment] 2015-11-20 18:33
You need to add:

```yaml
exclude:
  - vendor/
```

To your `_config.yml`

**Comment by charliesneath** [comment] 2015-11-20 18:35
Voila! That did it, thanks. 

Everything seems to be working as expected now.

**Comment by envygeeks** [comment] 2015-12-07 13:00
It seems this is resolved, closing this issue. Thanks for reporting!

**Closed by envygeeks** 2015-12-07 13:00 UTC
Labels: enhancement, ★★★
