### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by ikus060** [jekyll/jekyll-assets#231] opened 2016-01-09 18:36 UTC
Trying to use jekyll-assets for the first time. The build is failling with the following error:
```
$ bundler exec jekyll build --trace
Configuration file: /home/ikus060/workspace/WWW/pdsl-www.git/_config.yml
            Source: /home/ikus060/workspace/WWW/pdsl-www.git
       Destination: /home/ikus060/workspace/WWW/pdsl-www.git/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:112:in `fetch': no implicit conversion of String into Integer (TypeError)
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:112:in `compress?'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hooks/compression.rb:6:in `block in <top (required)>'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:50:in `instance_eval'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:50:in `block in initialize'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hook.rb:39:in `call'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hook.rb:39:in `block in trigger'
	from /usr/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /usr/lib/ruby/2.1.0/set.rb:263:in `each'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hook.rb:38:in `map'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hook.rb:38:in `trigger'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:49:in `initialize'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hooks/jekyll/setup.rb:6:in `new'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hooks/jekyll/setup.rb:6:in `block in <top (required)>'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/hooks.rb:97:in `call'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/hooks.rb:97:in `block in trigger'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/hooks.rb:96:in `each'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/hooks.rb:96:in `trigger'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:88:in `reset'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:56:in `process'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/bin/jekyll:23:in `load'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/bin/jekyll:23:in `<main>'
```

Trying to build the website as follow:
```
$ bundler install
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Installing addressable 2.4.0
Installing colorator 0.1
Installing concurrent-ruby 1.0.0
Installing fastimage 1.8.1
Installing ffi 1.9.10
Installing sass 3.4.20
Installing jekyll-sass-converter 1.4.0
Installing rb-fsevent 0.9.7
Installing rb-inotify 0.9.5
Installing listen 3.0.5
Installing jekyll-watch 1.3.0
Installing kramdown 1.9.0
Installing liquid 3.0.6
Installing mercenary 0.3.5
Installing rouge 1.10.1
Installing safe_yaml 1.0.4
Installing jekyll 3.0.1
Installing rack 1.6.4
Installing sprockets 3.5.2
Installing sprockets-helpers 1.2.1
Installing tilt 2.0.2
Installing jekyll-assets 2.1.2
Using bundler 1.7.4
Your bundle is complete!
It was installed into ./vendor/bundle
```

**Comment by ikus060** [comment] 2016-01-09 19:13
After some trial and error, it seams related to `_config.yml`:
```
assets:
  compress:
     - css: true
      - js: true
```
I don't get what is wrong ?!

**Comment by envygeeks** [comment] 2016-01-09 19:43
It doesn't seem like you did, this is probably a bug on my end.

**Comment by envygeeks** [comment] 2016-01-09 19:44
Until I can look at it and test it to see if I can replicate you can work around it by just removing those options, we automatically compress for you in production builds with JEKYLL_ENV=production.

**Comment by ikus060** [comment] 2016-01-09 19:45
Yep, I currently comments the lines to get the build working:
```
#  compress:
#     - css: true
#      - js: true
```

**Comment by envygeeks** [comment] 2016-01-10 15:53
Can you please provide a repository with a replication so that a case can be created, thanks.

**Comment by ikus060** [comment] 2016-01-10 16:50
Has request
[TEST.zip](https://github.com/jekyll/jekyll-assets/files/84185/TEST.zip)

**Comment by envygeeks** [comment] 2016-01-10 16:54
I'm not saying you would but my own policies typically prevent me from downloading unverified zips.  Is there any way you can commit that to a temporary repository I can verify before I clone?  You can delete it once I've confirmed and fixed or rejected and wontfix.

**Comment by ikus060** [comment] 2016-01-10 16:57
https://github.com/ikus060/jekyll-assets-issue-231

**Comment by envygeeks** [comment] 2016-01-10 16:59
Awesome, I'll check this out this afternoon and see what I can figure out.

**Comment by torbjoernk** [comment] 2016-01-12 20:21
@ikus060 I might be stupid, but aren't the dashes in front of `css` and `js` creating a list of maps instead of just a map for `compress`?
```
compress:
  - css: true
  - js: true
```
will read
```
{
  compress: [
    {
      css: true
    },
    {
      js: true
    }
  ]
}
```
while without the dashes it'll become
```
{
  compress: {
    css: true,
    js: true
  }
}
```

**Comment by envygeeks** [comment] 2016-01-12 20:23
Well spotted, I didn't even notice that.  does it work if you do as @torbjoernk suggested?

**Comment by ikus060** [comment] 2016-01-20 14:40
Ho yeah, I've add the dash because I got this error:
```
/home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `parse': (/home/ikus060/workspace/WWW/pdsl-www.git/_config.yml): mapping values are not allowed in this context at line 99 column 9 (Psych::SyntaxError)
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `load'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:157:in `block in load_file'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:157:in `open'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:157:in `load_file'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/configuration.rb:121:in `safe_load_file'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/configuration.rb:155:in `read_config_file'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/configuration.rb:180:in `block in read_config_files'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/configuration.rb:179:in `each'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/configuration.rb:179:in `read_config_files'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll.rb:102:in `configuration'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:42:in `configuration_from_options'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:29:in `process'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/bin/jekyll:23:in `load'
	from /home/ikus060/workspace/WWW/pdsl-www.git/vendor/bundle/ruby/2.1.0/bin/jekyll:23:in `<main>'
```
When using this configuration:
```
assets:
  compress:
    css: true
     js: true
```

**Comment by envygeeks** [comment] 2016-01-21 13:48
Try removing the alignment of keys and see if that fixes it.

**Comment by envygeeks** [comment] 2016-04-30 00:50
Closing this as fixed since there hasn't been a response.  If this continues to be a problem, please ping.

**Closed by envygeeks** 2016-04-30 00:50 UTC
Labels: bug, priority:low
