### ISSUE TITLE
Unknown tag 'stylesheet'

### ISSUE THREAD

**Issue by yordis** [jekyll/jekyll-assets#308] opened 2016-07-24 11:44 UTC
I followed the documentation but it didn't work for me.
What I did so far:

Added `gem 'jekyll-assets'` to my `Gemfile`
```
source 'https://rubygems.org'

gem 'jekyll', '~> 3.1'
gem 'jekyll-assets'

group :jekyll_plugins do
  gem 'github-pages', '~> 87'
end
```

2. Added `gems: - jekyll-assets` to my `_config.yml`
```
gems:
  - jekyll-assets

# Build settings
markdown: kramdown
highlighter: rouge

assets:
  prefix: /assets
  assets:
    - '*.css'
  digest: true
  sources:
    - docs/_assets
    - dist

# Site
title: Boa CSS Framework

# Server
source:           docs
destination:      _gh_pages
host:             localhost
port:             9001
baseurl:          ''
url:              http://caribbeanpirates.github.io/boa
encoding:         UTF-8
```

3. Used it
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    {% if page.title %}
      {{ page.title | escape }}
    {% else %}
      {{ site.title | escape }}
    {% endif %}
  </title>

  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

  {% stylesheet 'css/site.css' %}
</head>
```

It didn't work
<img width="2042" alt="screen shot 2016-07-24 at 7 43 30 am" src="https://cloud.githubusercontent.com/assets/4237280/17083537/5a08a240-5172-11e6-9f25-bd2359b5bd16.png">

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.0.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    colorator (0.1)
    concurrent-ruby (1.0.2)
    ethon (0.9.0)
      ffi (>= 1.3.0)
    execjs (2.7.0)
    extras (0.1.0)
      forwardable-extended (~> 2.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fastimage (2.0.0)
      addressable (~> 2)
    ffi (1.9.14)
    forwardable-extended (2.6.0)
    gemoji (2.1.0)
    github-pages (87)
      github-pages-health-check (= 1.1.0)
      jekyll (= 3.1.6)
      jekyll-coffeescript (= 1.0.1)
      jekyll-feed (= 0.5.1)
      jekyll-gist (= 1.4.0)
      jekyll-github-metadata (= 2.0.2)
      jekyll-mentions (= 1.1.3)
      jekyll-paginate (= 1.1.0)
      jekyll-redirect-from (= 0.11.0)
      jekyll-sass-converter (= 1.3.0)
      jekyll-seo-tag (= 2.0.0)
      jekyll-sitemap (= 0.10.0)
      jemoji (= 0.6.2)
      kramdown (= 1.11.1)
      liquid (= 3.0.6)
      listen (= 3.0.6)
      mercenary (~> 0.3)
      rouge (= 1.11.1)
      terminal-table (~> 1.4)
    github-pages-health-check (1.1.0)
      addressable (~> 2.3)
      net-dns (~> 0.8)
      octokit (~> 4.0)
      public_suffix (~> 1.4)
      typhoeus (~> 0.7)
    html-pipeline (2.4.2)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    i18n (0.7.0)
    jekyll (3.1.6)
      colorator (~> 0.1)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-assets (2.2.7)
      extras (~> 0.1)
      fastimage (~> 2.0, >= 1.8)
      jekyll (~> 3.1, >= 3.0)
      pathutil (>= 0.8)
      sprockets (~> 3.3)
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-feed (0.5.1)
    jekyll-gist (1.4.0)
      octokit (~> 4.2)
    jekyll-github-metadata (2.0.2)
      jekyll (~> 3.1)
      octokit (~> 4.0)
    jekyll-mentions (1.1.3)
      html-pipeline (~> 2.3)
      jekyll (~> 3.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.11.0)
      jekyll (>= 2.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-seo-tag (2.0.0)
      jekyll (~> 3.1)
    jekyll-sitemap (0.10.0)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    jemoji (0.6.2)
      gemoji (~> 2.0)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0)
    kramdown (1.11.1)
    liquid (3.0.6)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    mercenary (0.3.6)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    multipart-post (2.0.0)
    net-dns (0.8.0)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    octokit (4.3.0)
      sawyer (~> 0.7.0, >= 0.5.3)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    pkg-config (1.1.7)
    public_suffix (1.5.3)
    rack (2.0.1)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.22)
    sawyer (0.7.0)
      addressable (>= 2.3.5, < 2.5)
      faraday (~> 0.8, < 0.10)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    terminal-table (1.6.0)
    thread_safe (0.3.5)
    typhoeus (0.8.0)
      ethon (>= 0.8.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  github-pages (~> 87)
  jekyll (~> 3.1)
  jekyll-assets

BUNDLED WITH
   1.12.5
```
/cc: @envygeeks

**Comment by yordis** [comment] 2016-07-24 12:17
I didn't do anything and start working but now it takes 46s when it was like 8s

**Comment by envygeeks** [comment] 2016-08-05 13:33
Is the source available anywhere?

**Comment by yordis** [comment] 2016-08-05 16:58
Sorry @envygeeks I removed it :( Just a little feedback, even I tried to register someother tag and `Liquid` complains as well, like for some reason wasn't picking up those things. Just an observation!

But I removed

**Comment by envygeeks** [comment] 2016-08-06 00:50
Alright, closing this since we cannot reproduce it here.

**Closed by envygeeks** 2016-08-06 00:50 UTC
Labels: cant-reproduce
