### ISSUE TITLE
LiquidException: Unknown proxy argument

### ISSUE THREAD

**Issue by ShintaroNippon** [jekyll/jekyll-assets#330] opened 2016-09-06 09:11 UTC
Thanks by your anwser... the warning disappear however with this line of code
 `<img data-animate="zoomIn" srcset='{{ "device1.png magick:resize:549x395 magick:quality:100" | asset_path }} 1024w, {{ "device1.png magick:resize:280x201 magick:quality:100" | asset_path }} 640w' src='{{ "device1.png magick:resize:549x395 magick:quality:100" | asset_path }}' alt="Mac" style="width: 100%; top: 0; left: 0;">`

i'm getting another error

> LiquidException: Unknown proxy argument. in index.html
> 09:50:56 web.1 | jekyll 3.2.1 | Error: Unknown proxy argument.

**Comment by basex** [comment] 2016-10-07 13:02
@envygeeks any idea what might be? I required mini_magick and I'm having the same problem "Unknown proxy argument".

My liquid:
```liquid
{% asset_path 'test.png' magick:resize:100x100 %}
```

Tried to put the liquid in other ways, but the problem persists. Can't get the `magick:resize` to work.

**Comment by envygeeks** [comment] 2016-10-07 13:09
I have no idea what it could be but I'll look into it sometime in the next few days when I have time.  We've not changed anything here and we do test the structure of that, unless something has broken in Liquid that we need to account for but I don't think that happened.

**Comment by basex** [comment] 2016-10-07 13:33
I tried to use liquid tag img instead and the resized image is correctly created. So the problem is related with asset_path not working with the proxy arguments.

On the documentation it's written:

> Image Magick - add "mini_magick" to your Gemfile, only works with img, image.

but on the footer of the README after "supported helpers" there are the "Image Magick Proxy arguments", that's the confusing part for me. Should the arguments work with these helpers?

**Comment by sheck** [comment] 2016-11-10 19:24
I think I'm running into the same problem

`{% img 'map-bg.jpg' magick:resize:300x %}` returns the resized image in the <img> tag

`{% asset_path 'map-bg.jpg' magick:resize:300x %}` returns `Liquid Exception: Unknown proxy argument.`

Is there a filter or another way to extract the resized image's path from the <img> tag?

**Comment by basex** [comment] 2016-12-06 18:00
Anyone managed to make asset_path work with image magick?

**Comment by sheck** [comment] 2016-12-07 17:27
@basex I was able to get it using by creating a plugin similar to the one in this comment: https://github.com/jekyll/jekyll-assets/issues/199#issuecomment-170295836

**Comment by envygeeks** [comment] 2016-12-07 22:42
Man, I really gotta get ontop of bugs in jekyll-assets, I'll take a look at what you did and merge it in (with credit of course... if you are cool with that @sheck )

**Comment by envygeeks** [comment] 2017-10-08 07:33
This is resolved in 3.x.

**Closed by envygeeks** 2017-10-08 07:33 UTC
Labels: accepted, bug, enhancement
