### ISSUE TITLE
Scripts containing double curly braces end up corrupted

### ISSUE THREAD

**Issue by JaimeObregon** [jekyll/jekyll-assets#268] opened 2016-05-01 00:59 UTC
I'm not familiar with Rails nor Sprockets, but it seems something is badly broken somewhere in the stack, because JavaScript files containing `{{` or `}}` end up corrupted after being processed with `jekyll-assets`.

Although I have reproduced this behaviour with other scripts, I'm using `mustache.js` as a test case. [Line 571](https://raw.githubusercontent.com/janl/mustache.js/master/mustache.js#L571) says:

    mustache.tags = [ '{{', '}}' ];

Which after being processed by `jekyll-assets` ends up as:

    mustache.tags = [ ', ' ];

I might be wrong, but I suppose `jekyll-assets` just feeds the script contents to `UglifyJS`, which [in turn](https://marijnhaverbeke.nl/uglifyjs) seems to be doing it's work correctly.

**Comment by envygeeks** [comment] 2016-05-01 01:53
It seems to me that you have Liquid processing enable for that file.  Disable it and if you aren't on the latest stable of Jekyll-Assets update so you can disable it, because current stable has it disabled by default and only enabled for all files if you explicitly set it so, otherwise we require "..liquid"

**Comment by JaimeObregon** [comment] 2016-05-01 09:30
Thank you. I ran `gem install jekyll-assets` yesterday, which installed 2.1.2. I'm using the default settings; my `_config.yml` part regarding `jekyll-assets` only contains:

    assets:
        sources:
            - "_assets/lib"

I'm afraid I can't disable Liquid processing sufixing them with `.liquid`, because most of the scripts I'm minifying and concatenating are vendor files installed via Bower, and any change I made to them would be overwritten in the next dependency `update` or `install`.

**Comment by envygeeks** [comment] 2016-05-01 10:31
You cannot disable processing of ".liquid" extension.  You disable Liquid processing of the lack thereof as noted in the documentation.  Since your configuration does not enable Liquid I'm going to assume this is not a bug in Jekyll-Assets (that doesn't mean I won't try to see where the problem is.)  We do not process your assets more than ship them to Sprockets in the case of JavaScript... unless it  is ".js.liquid" which in-case we will process with Liquid... if you do that intentionally make it ".js.liquid" then this is a WONTFIX as there is nothing we can do about that, it's on you to escape the file at that point.

You can prepare a test case if you like, and I'll happily have my bot test and see if it can reproduce the problem, but as I said, we don't heavily process JS, you ask us to load the base file, we load it, Sprockets does the concatenation (requiring), sprockets does the processing, Sprockets even handles the minifying through UglifyJS.

Though, like I said, please do prepare a test-case, I'll happily look into the problem, but at this point I assume, it's not a bug in Jekyll-Assets directly and might need to go to an upstream somewhere.

**Comment by envygeeks** [comment] 2016-05-01 10:38
I've just dropped the exact file you linked to into my own site and ran Jekyll-Assets and am unable to reproduce the problem you're having directly, even with Uglifier processing the asset and minifying it.

**Comment by JaimeObregon** [comment] 2016-05-01 14:47
I have prepared a test case and detailed the steps to reproduce the issue. It is available at [JaimeObregon/jekyll-assets-test-case](//github.com/JaimeObregon/jekyll-assets-test-case).

I agree that this may not be an issue in Jekyll-Assets itself, but in other components of the workflow, or even a misconfiguration on my side. All in all, with my current understanding of Sprockets I haven't been able to dig deeper into it.

**Comment by JaimeObregon** [comment] 2016-05-07 19:41
I'd suggest removing the `cant-reproduce` tag.

**Comment by envygeeks** [comment] 2016-05-07 20:47
The bot will remove the tag once I have time to shim your example and reproduce it. Until then as long as it's open with a cant-reproduce it reminds me that I need to look into it because only cases that are tested wholly unreproducable get closed.

**Comment by JaimeObregon** [comment] 2016-05-09 15:36
Thank you for your clarification. Today I started over with a fresh install of everything, including updating to Jekyll 3.1.3, jekyll-assets 2.2.5 and uglifier 3.0.0, and I'm happy to say that I cannot reproduce this issue anymore.

My former setup wasn't very old, but whatever it was causing the corruption, it isn't anymore 😀

**Comment by envygeeks** [comment] 2016-05-21 06:16
Closing this out, thanks for updating to let us know it works on a clean site! Hope you can get it fixed for your current site and if you continue to have trouble you can always ask for help figuring out the problem on https://talk.jekyllrb.com (until we can reproduce a bug!)

**Closed by envygeeks** 2016-05-21 06:16 UTC
Labels: bug, cant-reproduce
