### ISSUE TITLE
asset_path from a magick resized image

### ISSUE THREAD

**Issue by mykagrove** [jekyll/jekyll-assets#225] opened 2015-12-15 14:41 UTC
Hi, sorry if this is a duplicate or just a non-existant feature.
I'm using the Jekyll 3 assets and want to get the asset path to a resized image, I've tried a few things along the lines of
```
{{ 'test.jpg' | img : "magick:resize:25%" | asset_path }}
{{ 'test.jpg' | append: ' | img : "magick:resize:25%"' | asset_path }}
```
But no joy :)

**Comment by envygeeks** [comment] 2015-12-15 15:04
Complicated logic like that will probably never be doable, all things considered Proxies are ran outside of proxies, not as a part of them because I didn't feel that Sprockets API was tidy enough for me to build them into Sprockets, so we actually pull out your asset and then proxy independently as part of the final step in the pipeline.  This might change with Sprockets 4 but I've yet to even see anything resembling a release date there.

That said, this is a direct duplicate of https://github.com/jekyll/jekyll-assets/issues/199 so I'm going to close this in favor of that that is asking for us to allow `{% asset_path asset | filters %}`.

**Closed** 2015-12-15 15:04 UTC
